apiVersion: v1
kind: PersistentVolume
metadata:
  name: netdata-database-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  local:
    path: /mnt/netdata-database
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: sym-preserve
              operator: In
              values:
                - middleware
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: netdata-alarms-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  local:
    path: /mnt/netdata-alarms
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: sym-preserve
              operator: In
              values:
                - middleware
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem