ingress:
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - monitor.netdata.dmall.com


master:
  resources:
    limits:
      cpu: 1
      memory: 1024Mi
    requests:
      cpu: 1
      memory: 1024Mi
  database:
    storageclass: local-storage
  alarms:
    storageclass: local-storage

slave:
  resources:
    limits:
      cpu: 0.5
      memory: 512Mi
    requests:
      cpu: 0.5
      memory: 512Mi