ingress:
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - monitor.netdata.dmall.com


master:
  resources:
    limits:
      cpu: 1
      memory: 2048Mi
    requests:
      cpu: 1
      memory: 2048Mi
  database:
    storageclass: local-storage
  alarms:
    storageclass: local-storage

slave:
  resources:
    limits:
      cpu: 0.5
      memory: 512Mi
    requests:
      cpu: 0.5
      memory: 512Mi
  tolerations:
    - operator: Exists
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - 10.28.27.242