apiVersion: workload.dmall.com/v1beta1
kind: Cluster
metadata:
  labels:
    clusterName: dev-df-hk-01
    createdBy: sym-controller
  name: dev-df-hk-01
  namespace: sym-admin
spec:
  symNodeName: 10.248.224.157
  pause: false
  meta:
    area: hongkong
    az: hk
    clusterType: tke
    clusterIngressHead: monitor
  helmSpec:
    maxHistory: 5
    namespace: kube-system
    overrideImageSpec: registry.cn-hangzhou.aliyuncs.com/google_containers/tiller:v2.13.1
  apps:
    - name: metrics-server
      repo: dmall
      namespace: monitoring
    - name: traefik
      repo: dmall
      namespace: kube-system
      chartVersion: 1.86.1
    - name: monitor
      repo: dmall
      namespace: monitoring
      chartName: prometheus-operator
      chartVersion: 8.7.1
      values:
        custom-resources-config: disable
        selector-only-system: enable
        lpv-path: /root/prometheus-data
        lpv-size: 20Gi
        prom-limit-cpu: "1"
        prom-limit-memory: 2Gi
        prom-req-cpu: "0.5"
        prom-req-memory: 1Gi
        prom-retention: 2d
        lpv-grafana-path: /root/grafana-data
        lpv-grafana-size: 1Gi
        grafana-ing: mg.sym.inner-dmall.com.hk
        prom-ing: mp.sym.inner-dmall.com.hk
        alertmanager-ing: ma.sym.inner-dmall.com.hk
    - name: sym-api
      repo: dmall
      namespace: sym-admin
      chartName: sym-api
      chartVersion: 1.0.16
      values:
        hosts: devapi.sym.inner-dmall.com.hk
        tag: "v1.0.10"
    - name: sym-ctl
      repo: dmall
      namespace: sym-admin
      chartName: sym-controller
      chartVersion : 1.0.16
      values:
        tag: "v1.0.10"
        master: "true"
        worker: "true"
        cluster: "false"
        reCreate: "true"
        leader: "true"
        oldCluster: "false"
        threadiness: "1"