apiVersion: workload.dmall.com/v1beta1
kind: AppSet
metadata:
  name: bbcc
  namespace: default
spec:
  replicas: 10
  podSpec:
    deployType: helm
    chart:
      chartUrl:
        url: dmall/springBoot
        chartVersion: 0.0.1
  serviceName: bbcc-svc
  updateStrategy:
    upgradeType: canary|blue|green
    minReadySeconds: 10
    canaryClusters:
      - tcc-bj4-dks-test-01
    needWaitingForConfirm: true
    paused: false
  clusterTopology:
    clusters:
      - name: tcc-bj4-dks-test-01
        meta:
          area: beijing
          az: bj4
          ldc: TCC_BJ4_DKS_TEST_01
        podSets:
          - name: bbcc-gz01b-canary
            replicas: 1
            version: v1
            meta:
              app: bbcc
              version: v1
              sym-group: canary
              sym-ldc: gz01b
          - name: bbcc-gz01b-blue
            replicas: 2
            version: v1
            meta:
              app: bbcc
              version: v1
              sym-group: blue
              sym-ldc: gz01b
          - name: bbcc-gz01b-green
            replicas: 2
            version: v1
            meta:
              app: bbcc
              version: v1
              sym-group: green
              sym-ldc: gz01b
      - name: tcc-bj5-dks-test-01
        meta:
          area: beijing
          az: bj5
          ldc: TCC_BJ5_DKS_TEST_01
        podSets:
          - name: bbcc-gz01a-canary
            replicas: 1
            version: v2
            meta:
              app: bbcc
              version: v2
              sym-group: canary
              sym-ldc: gz01a
          - name: bbcc-gz01a-blue
            replicas: 2
            version: v1
            meta:
              app: bbcc
              version: v1
              sym-group: blue
              sym-ldc: gz01a
          - name: bbcc-gz01a-green
            replicas: 2
            version: v1
            meta:
              app: bbcc
              version: v1
              sym-group: green
              sym-ldc: gz01a