apiVersion: workload.dmall.com/v1beta1
kind: AppSet
metadata:
  name: nginx
  namespace: default
spec:
  replicas: 10
  podSpec:
    deployType: helm
    chart:
      url: dmall/nginx
  serviceName: nginx-svc
  updateStrategy:
    upgradeType: canary|blue|green
    minReadySeconds: 10
    canaryClusters:
      - tcc-bj4-dks-test-01
    needWaitingForConfirm: true
    paused: false
  clusterTopology:
    - name: tcc-bj4-dks-test-01
      meta:
        area: beijing
        az: bj4
        ldc: TCC_BJ4_DKS_TEST_01
      podSets:
        - name: nginx-gz01b-canary
          replicas: 1
          version: v2
          meta:
            app: nginx
            version: v2
            sym-group: canary
            sym-ldc: gz01b
        - name: nginx-gz01b-blue
          replicas: 2
          version: v1
          meta:
            app: nginx
            version: v1
            sym-group: blue
            sym-ldc: gz01b
        - name: nginx-gz01b-green
          replicas: 2
          version: v1
          meta:
            app: nginx
            version: v1
            sym-group: green
            sym-ldc: gz01b
    - name: tcc-bj5-dks-test-01
      meta:
        area: beijing
        az: bj5
        ldc: TCC_BJ5_DKS_TEST_01
      podSets:
        - name: nginx-gz01a-canary
          replicas: 1
          version: v2
          meta:
            app: nginx
            version: v2
            sym-group: canary
            sym-ldc: gz01a
        - name: nginx-gz01a-blue
          replicas: 2
          version: v1
          meta:
            app: nginx
            version: v1
            sym-group: blue
            sym-ldc: gz01a
        - name: nginx-gz01a-green
          replicas: 2
          version: v1
          meta:
            app: nginx
            version: v1
            sym-group: green
            sym-ldc: gz01a