apiVersion: workload.dmall.com/v1beta1
kind: AppSet
metadata:
  name: bbcc
  namespace: default
spec:
  replicas: 8
  podSpec:
    deployType: helm
    chart:
      chartUrl:
        url: dmall/springBoot
  serviceName: inner.bbcc.dmall.com
  updateStrategy:
    upgradeType: canary|blue|green
    minReadySeconds: 10
    canaryClusters:
      - tcc-bj4-dks-test-01
    needWaitingForConfirm: true
    paused: false
  clusterTopology:
    clusters:
      - name: tcc-bj5-dks-monit-01
        meta:
          sym-available-zone: bj5
          sym-cluster-info: tcc-bj5-dks-monit-01
        podSets:
          - name: bbcc-gz01b-blue
            replicas: 2
            version: v3
            image: registry.cn-hangzhou.aliyuncs.com/dmall/bbcc
            meta:
              sym-group: blue
              sym-ldc: gz01b
          - name: bbcc-gz01b-green
            replicas: 2
            version: v3
            image: registry.cn-hangzhou.aliyuncs.com/dmall/bbcc
            meta:
              sym-group: green
              sym-ldc: gz01b
      - name: tcc-bj5-dks-test-01
        meta:
          sym-available-zone: bj5
          sym-cluster-info: tcc-bj5-dks-test-01
        podSets:
          - name: bbcc-gz01a-blue
            replicas: 2
            version: v3
            image: registry.cn-hangzhou.aliyuncs.com/dmall/bbcc
            meta:
              sym-group: blue
              sym-ldc: gz01a
          - name: bbcc-gz01a-green
            replicas: 2
            version: v3
            image: registry.cn-hangzhou.aliyuncs.com/dmall/bbcc
            meta:
              sym-group: green
              sym-ldc: gz01a