apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1UQXhOVEE0TWpFeU9Wb1hEVEk1TVRBeE1qQTRNakV5T1Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBUGFDCmIraGQycGs2dWt1S25FVVF6NFhsWFNoaGhUK3I2WEJXZEphUjZFeHdwTG1uRWRLQXE1N3hnWDNzYUJXMnJFencKOERXMzFIeTAvbnAremFqLzhjRlhYZUFYbzdicGhSbmtaUHIxenJPdUd2OFcxMVRRNUw3bkpDVFAwVGVzTUFOOQpPK3hsUVZ2WDk4VVY3bTVUVXE1V3MxSmU5eFRZRG9IYnQ2SmdObE9abnV4V1VJN1BvaWRHbW9JamtzdjZtNUxmCi94Z2VyRDNkN0l2NWJyWXI4Rjl6NDNmTkFYeHkwL3lQQ0JZbVNYR2x1cFJVTW8rQnZydHREN21hOXhuam5vaFQKRDIvN0tWd3FpRG9iamdrbG5Jdmo2QytpdkFCd0VzSThoWW54OWdNcExRQTByU0NhUURCV0grQUhCRXVheklBawpiU3V0SWlqdjJlc3JtRkYrcG5zQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0tVTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFGR2E5dkJpNDd0NUpvNjRBdWVCbEhxN3hTcWEKRWtvRkJ6QWk5NzltOVdvY2R2Zy9HZDQ3UzF4SzY5NjVqd2ovNm5ub0FlMlFPZEQzbTBhWC9Md3RUc2RFRlJnYgplckJBcnBKNFp5L1BRZGlkZUJ0dVhFanpqNDBWN2xFemg3aVBCWmdQaGVrTnBvVkFJUGFvZ2JtK1pZUlZVQjZhCm44ZXN6YlpkTlYwN3NEWCtnSUZYZ01Dd0ZUOVJVeXBOM2ZXQ1ljTFJNRVJVU215SGROZVpEOExreFlEY3lTY1cKclJhSDVqWWZRZVh5WXNtUXdGcXZsaDlMNnB3ZG85Ym1mcklRYVk4T0x5TDlobmpxY2JtZlVtMDNYUWlvMVdWNwpFaFhwZ0FRQzlhNDlTdkdKakJsSEVRQUhEU1VWV0hJTVV3cGxLd2pLeXNOQzM5QTdsclFCbXRmZmhzdz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      server: 'https://cls-7xq1bq9f.ccs.tencent-cloud.com'
    name: tcc-bj5-dks-test-01-cluster
contexts:
  - context:
      cluster: tcc-bj5-dks-test-01-cluster
      user: tcc-bj5-dks-test-01-admin
    name: tcc-bj5-dks-test-01-system
current-context: tcc-bj5-dks-test-01-system
kind: Config
preferences: {}
users:
  - name: tcc-bj5-dks-test-01-admin
    user:
      password: hb69NVhyLwNldInEaHGiEjni6mxzvwPM
      username: admin