# permissions to do viewer advdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: advdeployment-viewer-role
rules:
- apiGroups:
  - workload.dmall.com
  resources:
  - advdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - workload.dmall.com
  resources:
  - advdeployments/status
  verbs:
  - get
