# permissions to do edit advdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: advdeployment-editor-role
rules:
- apiGroups:
  - workload.dmall.com
  resources:
  - advdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workload.dmall.com
  resources:
  - advdeployments/status
  verbs:
  - get
  - patch
  - update
