apiVersion: {{ include "deployment_api_version" . }}
kind: Deployment
metadata:
  name: {{ include "controller.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "controller.name" . }}
    helm.sh/chart: {{ include "controller.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "controller.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "controller.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
          - "controller"
          - "-v"
          - {{ .Values.image.logLevel | quote | default "4" }}
          {{- if .Values.image.master }}
          - "--enable-worker"
          {{- end }}
          {{- if .Values.image.worker }}
          - "--enable-worker"
          {{- end }}
          {{- if .Values.image.debug }}
          - "--debug"
          {{- end }}
          
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.healthPath.liveness }}
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: {{ .Values.healthPath.readiness }}
              port: http
            initialDelaySeconds: 5
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      serviceAccountName: {{ .Values.rbac.name }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
    {{- end }}
