apiVersion: workload.dmall.com/v1beta1
kind: Cluster
metadata:
  labels:
    clusterName: tcc-rz01-dev
    createdBy: sym-controller
  name: tcc-rz01-dev
  namespace: sym-admin
spec:
  symNodeName: 10.248.227.69
  pause: false
  meta:
    area: chengdu
    az: CD
    clusterType: tke
    clusterIngressHead: dev-rz-cd
  apps:
#    - name: metrics-server
#      repo: dmall
#      namespace: monitoring
    - name: contour
      repo: dmall
      namespace: projectcontour
      chartVersion: 1.1.4
    - name: monitor
      repo: dmall
      namespace: monitoring
      chartName: prometheus-operator
      chartVersion: 9.1.0
      values:
        istioScrape: enable
        custom-resources-config: disable
        selector-only-system: disable
        lpv-path: /root/prometheus-data
        lpv-size: 20Gi
        prom-limit-cpu: "4"
        prom-limit-memory: 8Gi
        prom-req-cpu: "0.5"
        prom-req-memory: 1Gi
        prom-retention: 2d
        lpv-grafana-path: /root/grafana-data
        lpv-grafana-size: 1Gi
