apiVersion: workload.dmall.com/v1beta1
kind: Cluster
metadata:
  labels:
    clusterName: dev-tke-rz-cd-glb
    createdBy: sym-controller
  name: dev-tke-rz-cd-glb
  namespace: default
spec:
  symNodeName: 10.248.227.69
  pause: false
  meta:
    area: chengdu
    az: CD
    id: "1"
    clusterType: tke
    clusterIngressHead: dks-test-rz-glb
  helmSpec:
    maxHistory: 5
    namespace: kube-system
    overrideImageSpec: registry.cn-hangzhou.aliyuncs.com/google_containers/tiller:v2.13.1
  apps:
    - name: metrics-server
      repo: dmall
      namespace: monitoring
    - name: traefik
      repo: dmall
      namespace: kube-system
      chartVersion: 1.86.1
    - name: monitor
      repo: dmall
      namespace: monitoring
      chartName: prometheus-operator
      chartVersion: 8.7.1
      values:
        custom-resources-config: disable
        selector-only-system: enable
        lpv-path: /root/prometheus-data
        lpv-size: 20Gi
        prom-limit-cpu: "4"
        prom-limit-memory: 8Gi
        prom-req-cpu: "0.5"
        prom-req-memory: 1Gi
        prom-retention: 2d
        lpv-grafana-path: /root/grafana-data
        lpv-grafana-size: 1Gi
    - name: sym-ctl
      repo: dmall
      namespace: sym-admin
      chartName: sym-controller
      chartVersion : 1.0.17
      values:
        tag: "v1.0.10"
        master: "false"
        worker: "true"
        cluster: "false"
        reCreate: "true"
        leader: "true"
        oldCluster: "false"
        threadiness: "1"
        repos: "https://kubernetes-charts.storage.googleapis.com"
