apiVersion: workload.dmall.com/v1beta1
kind: Cluster
metadata:
  labels:
    clusterName: tcc-gz02-dev
    createdBy: sym-controller
  name: tcc-gz02-dev
  namespace: sym-admin
spec:
  symNodeName: 10.248.227.132
  pause: false
  meta:
    area: beijing
    az: BJ
    clusterType: tke
    clusterIngressHead: dev-gz-bj
  apps:
    - name: metrics-server
      repo: dmall
      namespace: monitoring
    - name: contour
      repo: dmall
      namespace: projectcontour
      chartVersion: 1.1.
    - name: monitor
      repo: dmall
      namespace: monitoring
      chartName: prometheus-operator
      chartVersion: 9.1.0
      values:
        istioScrape: enable
        custom-resources-config: disable
        selector-only-system: disable
        lpv-path: /root/prometheus-data
        lpv-size: 20Gi
        prom-limit-cpu: "4"
        prom-limit-memory: 8Gi
        prom-req-cpu: "0.5"
        prom-req-memory: 1Gi
        prom-retention: 2d
        lpv-grafana-path: /root/grafana-data
        lpv-grafana-size: 1Gi
    - name: sym-api
      repo: dmall
      namespace: sym-admin
      chartName: sym-api
      chartVersion: 1.0.17
      values:
        hosts: testapi-glb.sym.dmall.com
        tag: "v1.1.0-dev16-3"
    - name: sym-ctl
      repo: dmall
      namespace: sym-admin
      chartName: sym-controller
      chartVersion : 1.0.18
      values:
        tag: "v1.1.0-dev16-3"
        master: "true"
        worker: "true"
        offlinepod: "true"
        cluster: "true"
        reCreate: "true"
        leader: "true"
        oldCluster: "false"
        threadiness: "1"
