apiVersion: workload.dmall.com/v1beta1
kind: Cluster
metadata:
  labels:
    clusterName: tcc-bj5-dks-monit-01
    createdBy: sym-controller
  name: tcc-bj5-dks-monit-01
  namespace: sym-admin
spec:
  symNodeName: 10.13.135.243
  pause: false
  meta:
    area: beijing
    az: bj5
    clusterType: tke
    clusterIngressHead: monitor
#    clusterIngressImpl: contour
  apps:
    - name: metrics-server
      repo: dmall
      namespace: monitoring
    - name: monitor
      repo: dmall
      namespace: monitoring
      chartName: prometheus-operator
      chartVersion: 9.1.0
      values:
        custom-resources-config: disable
        selector-only-system: disable
        lpv-path: /root/prometheus-data
        lpv-size: 20Gi
        prom-limit-cpu: "2"
        prom-limit-memory: 4Gi
        prom-req-cpu: "1"
        prom-req-memory: 2Gi
        prom-retention: 2d
        lpv-grafana-path: /root/grafana-data
        lpv-grafana-size: 1Gi
        grafana-ing: mg.symphony.dmall.com
        prom-ing: mp.symphony.dmall.com
        alertmanager-ing: ma.symphony.dmall.com
    - name: contour
      repo: dmall
      namespace: projectcontour
      chartVersion: 1.1.4
    - name: sym-api
      repo: dmall
      namespace: sym-admin
      chartName: sym-api
      chartVersion: 1.0.17
      values:
        hosts: devapi.sym.dmall.com
        tag: "v1.1.0-dev11"
    - name: sym-ctl
      repo: dmall
      namespace: sym-admin
      chartName: sym-controller
      chartVersion : 1.0.18
      values:
        tag: "v1.1.0-dev11"
        master: "true"
        worker: "true"
        offlinepod: "true"
        cluster: "false"
        reCreate: "true"
        leader: "true"
        threadiness: "1"

