apiVersion: workload.dmall.com/v1beta1
kind: Cluster
metadata:
  labels:
    clusterName: tcc-bj5-dks-test-01
    createdBy: sym-controller
  name: tcc-bj5-dks-test-01
  namespace: sym-admin
spec:
  symNodeName: 10.13.135.17
  pause: false
  meta:
    area: beijing
    az: bj5
    clusterType: tke
    clusterIngressHead: devt1
    clusterIngressImpl: contour
  apps:
    - name: metrics-server
      repo: dmall
      namespace: monitoring
    - name: monitor
      repo: dmall
      namespace: monitoring
      chartName: prometheus-operator
      chartVersion: 9.1.0
      values:
        custom-resources-config: disable
        selector-only-system: disable
        lpv-path: /web/prometheus-data
        lpv-size: 20Gi
        prom-limit-cpu: "1"
        prom-limit-memory: 4Gi
        prom-req-cpu: "0.5"
        prom-req-memory: 1Gi
        prom-retention: 2d
        lpv-grafana-path: /web/grafana-data
        lpv-grafana-size: 1Gi
    - name: contour
      repo: dmall
      namespace: projectcontour
      chartVersion: 1.1.4
    - name: sym-ctl
      repo: dmall
      namespace: sym-admin
      chartName: sym-controller
      chartVersion : 1.0.18
      values:
        tag: "v1.1.0-dev11"
        master: "false"
        worker: "true"
        cluster: "false"
        offlinepod: "false"
        reCreate: "true"
        leader: "true"
        threadiness: "1"
