package apiManager

// GetClusterDesc ...
var GetClusterDesc = `
get all cluster.
`

// GetPodDesc ...
var GetPodDesc = ``

// DeletePodDesc ...
var DeletePodDesc = ``

// DeletePodByGroupDesc ...
var DeletePodByGroupDesc = ``

// GetNodeProjectDesc ...
var GetNodeProjectDesc = ``

// GetEndpointsDesc ...
var GetEndpointsDesc = ``

// GetNodeInfoDesc ...
var GetNodeInfoDesc = ``

// GetTerminalDesc ...
var GetTerminalDesc = ``

// GetServicesDesc ...
var GetServicesDesc = ``

// GetDeploymentsDesc ...
var GetDeploymentsDesc = ``

// GetPodEventDesc ...
var GetPodEventDesc = ``

// HandleLogsDesc ...
var HandleLogsDesc = ``

// HandleFileLogsDesc ...
var HandleFileLogsDesc = ``
